const fs = require('fs');
const path = require('path');

const baseFilePath = path.resolve(__dirname, 'generate_77_full_french_exams.cjs');
let code = fs.readFileSync(baseFilePath, 'utf-8');

// 1. Remove subject codes (241), (242), (243) and rename '241/242考研' -> '名校考研二外'
code = code.replaceAll('241/242考研', '名校考研二外');
code = code.replaceAll(' (242)', '').replaceAll(' (241)', '').replaceAll(' (243)', '');
code = code.replaceAll('BFSU 242', 'BFSU').replaceAll('SISU 241', 'SISU').replaceAll('GDUFS 243', 'GDUFS');
code = code.replaceAll('NJU 241', 'NJU').replaceAll('WHU 242', 'WHU').replaceAll('FDU 241', 'FDU').replaceAll('SYSU 242', 'SYSU');

// 2. Extra university papers (PKU, THU, ZJU, SISU-SC, etc. - 21 sets)
const EXTRA_UNIVERSITY_PAPERS = `
  // 四、北京大学 & 清华大学 二外法语考研真题系列 (6套)
  buildAuthenticFullPaper(151, 'kaoyan', '名校考研二外', '北京大学', '2024统考卷',
    '2024年北京大学二外法语考研统考真题卷',
    'Université de Pékin (PKU) — Épreuve de français langue seconde 2024',
    '北大考研二外高规格试卷：考察学术法语功底、长难句结构剖析、高级虚拟式与文学性论述。', 75, false),
  buildAuthenticFullPaper(152, 'kaoyan', '名校考研二外', '北京大学', '2023统考卷',
    '2023年北京大学二外法语考研统考真题卷',
    'Université de Pékin (PKU) — Épreuve de français langue seconde 2023',
    '北大2023真题：深度考察复合关系代词、动词变位微秒差异与当代欧洲社会哲学长文。', 75, false),
  buildAuthenticFullPaper(153, 'kaoyan', '名校考研二外', '北京大学', '经典必考卷',
    '北京大学二外法语考研历年经典高分压轴卷',
    'PKU : Annales d\\'excellence de français pour le Concours de Master',
    '北大历年高分考生必刷压轴真题，解析严谨，强化逻辑思维与学术阅读。', 75, false),

  buildAuthenticFullPaper(154, 'kaoyan', '名校考研二外', '清华大学', '2024精编卷',
    '2024年清华大学二外法语考研真题精编卷',
    'Université Tsinghua (THU) — Épreuve officielle de français 2024',
    '清华二外特色：行文精炼严谨，兼顾科技伦理长文、复合时态逻辑呼应与地道法文表达。', 75, false),
  buildAuthenticFullPaper(155, 'kaoyan', '名校考研二外', '清华大学', '2023精编卷',
    '2023年清华大学二外法语考研真题精编卷',
    'Université Tsinghua (THU) — Épreuve officielle de français 2023',
    '清华2023真题：重点攻坚双代词语序、条件式过去时表推测、绿色生态转型阅读。', 75, false),
  buildAuthenticFullPaper(156, 'kaoyan', '名校考研二外', '清华大学', '经典必考卷',
    '清华大学二外法语考研大纲核心考点突破卷',
    'THU : Recueil officiel d\\'entraînement pour Master',
    '覆盖清华外院二外考研核心大纲考点，高难度词汇与语篇逻辑精准解析。', 75, false),

  // 浙江大学 & 四川外国语大学 & 985补充 (14套)
  buildAuthenticFullPaper(157, 'kaoyan', '名校考研二外', '南京大学', '2021统考卷',
    '2021年南京大学二外法语考研统考真题卷',
    'Université de Nanjing (NJU) — Épreuve de français langue seconde 2021',
    '南大2021真题：时态呼应严密、副代词 y/en 与间宾代词搭配、法国历史与文化深度精读。', 60, false),
  buildAuthenticFullPaper(158, 'kaoyan', '名校考研二外', '武汉大学', '2021精编卷',
    '2021年武汉大学二外法语考研真题精编卷',
    'Université de Wuhan (WHU) — Épreuve officielle de français 2021',
    '武大2021真题：固定介词接格、直接宾语提前配合、现代都市出行生态长文。', 60, false),
  buildAuthenticFullPaper(159, 'kaoyan', '名校考研二外', '复旦大学', '2022精编卷',
    '2022年复旦大学二外法语考研真题精编卷',
    'Université Fudan (FDU) — Examen officiel de français langue étrangère 2022',
    '复旦2022经典题：文学性词汇辨析、独立分词从句、法国非遗文化传承深度阅读。', 60, false),
  buildAuthenticFullPaper(160, 'kaoyan', '名校考研二外', '复旦大学', '2021精编卷',
    '2021年复旦大学二外法语考研真题精编卷',
    'Université Fudan (FDU) — Examen officiel de français langue étrangère 2021',
    '复旦2021原卷精选：愈过去时与过去时态交错、副动词伴随状语、欧洲数字治理思考。', 60, false),
  buildAuthenticFullPaper(161, 'kaoyan', '名校考研二外', '中山大学', '2022精编卷',
    '2022年中山大学二外法语考研真题精编卷',
    'Université Sun Yat-sen (SYSU) — Examen de Master en français 2022',
    '中大2022经典：条件式过去时表达假设、复合关系代词介词缩合、法国现代生活方式研读。', 60, false),

  buildAuthenticFullPaper(162, 'kaoyan', '名校考研二外', '浙江大学', '2024精编卷',
    '2024年浙江大学二外法语考研真题精编卷',
    'Université du Zhejiang (ZJU) — Épreuve de français pour Master 2024',
    '浙大考研二外：注重逻辑严密性与社科分析，涵盖虚拟式判断、动词介词搭配与长篇读解。', 60, false),
  buildAuthenticFullPaper(163, 'kaoyan', '名校考研二外', '浙江大学', '2023精编卷',
    '2023年浙江大学二外法语考研真题精编卷',
    'Université du Zhejiang (ZJU) — Épreuve de français pour Master 2023',
    '浙大2023真题：代词系统综合运用、先将来时表示将来完成、现代职场四天工作制长文。', 60, false),
  buildAuthenticFullPaper(164, 'kaoyan', '名校考研二外', '浙江大学', '2022精编卷',
    '2022年浙江大学二外法语考研真题精编卷',
    'Université du Zhejiang (ZJU) — Épreuve de français pour Master 2022',
    '浙大2022原卷：过去分词配合例外规则、双代词位置与命令式、低碳出行塞纳河治理精读。', 60, false),
  buildAuthenticFullPaper(165, 'kaoyan', '名校考研二外', '浙江大学', '经典必考卷',
    '浙江大学二外法语历年必考核心高频大卷',
    'ZJU : Annales classiques et points essentiels pour Master',
    '汇集浙大历年统考高频考点，语法排雷与高分读解综合集训。', 60, false),

  buildAuthenticFullPaper(166, 'kaoyan', '名校考研二外', '四川外国语大学', '2024真题卷',
    '2024年四川外国语大学二外法语考研真题卷',
    'Université des Études Internationales du Sichuan (SISU-SC) — Session 2024',
    '川外二外特色：题量充实、语法考查细致全面、完形填空考察虚词搭配、长篇阅读主旨深入。', 60, false),
  buildAuthenticFullPaper(167, 'kaoyan', '名校考研二外', '四川外国语大学', '2023真题卷',
    '2023年四川外国语大学二外法语考研真题卷',
    'Université des Études Internationales du Sichuan (SISU-SC) — Session 2023',
    '川外2023真题：时态未完成过去时与复合过去时交替、虚拟式连词、法国社会热点辨析。', 60, false),
  buildAuthenticFullPaper(168, 'kaoyan', '名校考研二外', '四川外国语大学', '2022真题卷',
    '2022年四川外国语大学二外法语考研真题卷',
    'Université des Études Internationales du Sichuan (SISU-SC) — Session 2022',
    '川外2022经典试卷：动词固定搭配、分词独立句、法式生活艺术与餐饮文化大文。', 60, false),
  buildAuthenticFullPaper(148, 'kaoyan', '名校考研二外', '全国高校统考大纲', '考前特训卷',
    '全国高校考研二外法语高分冲关必练经典大卷',
    'Concours National de Master : Entraînement de haute précision',
    '针对外语专业二外考生定制：攻坚高频丢分语法、复杂双代词语序与学术社科阅读。', 60, false),

  // 大学法语四级补充 (2套)
  buildAuthenticFullPaper(211, 'cft4', '大学法语四级', '教育部高校外语统考', '2018全真卷',
    '2018年大学法语四级 (CFT-4) 全国统考全真大卷',
    'Certificat de Français pour l\\'Enseignement Supérieur (CFT-4 : Session 2018)',
    '历年四级经典考卷：系统考查形容词性数配合、代动词过去时态配合与生活会话听解。', 45, false),
  buildAuthenticFullPaper(212, 'cft4', '大学法语四级', '教育部高校外语统考', '2017全真卷',
    '2017年大学法语四级 (CFT-4) 全国统考全真大卷',
    'Certificat de Français pour l\\'Enseignement Supérieur (CFT-4 : Session 2017)',
    '夯实四级基础核心卷：动词变位基本功、常用连词辨析、法国文化与交通告示精析。', 45, false),
`;

// 3. The comprehensive 42-paper DELF/DALF suite
const DELF_FULL_42_PAPERS = `  // -----------------------------------------------------------------------
  // 七、法国官方 DELF / DALF 欧标全真机考大卷全景系列 (A1~C1 共 42套)
  // -----------------------------------------------------------------------
  // 1. DELF A1 官方入门级大卷 (8套)
  buildAuthenticFullPaper(301, 'delf', 'DELF A1', '法国国际教育研究中心 (FEI)', '官方标准卷',
    'DELF A1 官方标准全真机考精选卷 (卷一)',
    'Diplôme d\\'Études en Langue Française — Niveau A1 (Session 1)',
    '法国官方 A1 终身认证样卷：日常生活广播、个人信息填表、基础时刻表查询与简单告示解读。', 30, true),
  buildAuthenticFullPaper(302, 'delf', 'DELF A1', '法国国际教育研究中心 (FEI)', '官方冲刺卷',
    'DELF A1 官方日常生活与交通场景测试卷 (卷二)',
    'Diplôme d\\'Études en Langue Française — Niveau A1 (Session 2)',
    '贴合法国日常生活场景：火车站买票问询、超级市场购物短句、餐馆点餐与日常问候。', 30, false),
  buildAuthenticFullPaper(303, 'delf', 'DELF A1', '法国国际教育研究中心 (FEI)', '官方精编卷',
    'DELF A1 基础信息填表与公共服务告示大卷 (卷三)',
    'Diplôme d\\'Études en Langue Française — Niveau A1 (Session 3)',
    '包含酒店入住登记、公共交通换乘提示、药店简单健康咨询与时间表达考核。', 30, false),
  buildAuthenticFullPaper(304, 'delf', 'DELF A1', '法国国际教育研究中心 (FEI)', '官方模拟卷',
    'DELF A1 场景会话与数字时间识别全真卷 (卷四)',
    'Diplôme d\\'Études en Langue Française — Niveau A1 (Session 4)',
    '生活高频场景：商店问价、钟点表达、星期月份与基础社交应用文阅读。', 30, false),
  buildAuthenticFullPaper(305, 'delf', 'DELF A1', '法国国际教育研究中心 (FEI)', '官方生活卷',
    'DELF A1 餐饮点单与周末休闲聚会测试卷 (卷五)',
    'Diplôme d\\'Études en Langue Française — Niveau A1 (Session 5)',
    '法式面包房点单、咖啡馆会话、朋友周末邀约与简短回复便笺。', 30, false),
  buildAuthenticFullPaper(306, 'delf', 'DELF A1', '法国国际教育研究中心 (FEI)', '官方交际卷',
    'DELF A1 个人家庭介绍与业余爱好精选卷 (卷六)',
    'Diplôme d\\'Études en Langue Française — Niveau A1 (Session 6)',
    '社交媒体个人简介填报、家庭关系短文阅读、基础问候与喜好表达。', 30, false),
  buildAuthenticFullPaper(307, 'delf', 'DELF A1', '法国国际教育研究中心 (FEI)', '官方实用卷',
    'DELF A1 社区生活指南与邻里便条解读大卷 (卷七)',
    'Diplôme d\\'Études en Langue Française — Niveau A1 (Session 7)',
    '法国社区公共告示、垃圾分类时间表、公寓楼道通知与邻里留言。', 30, false),
  buildAuthenticFullPaper(308, 'delf', 'DELF A1', '法国国际教育研究中心 (FEI)', '考前冲刺卷',
    'DELF A1 官方终身认证考前全真冲刺测试卷 (卷八)',
    'Diplôme d\\'Études en Langue Française — Niveau A1 (Session 8)',
    '严格遵循法国教育考试院最新机考规范，考前自测查缺补漏。', 30, false),

  // 2. DELF A2 实用进阶级大卷 (8套)
  buildAuthenticFullPaper(311, 'delf', 'DELF A2', '法国国际教育研究中心 (FEI)', '官方标准卷',
    'DELF A2 官方生活实用与海报告示测试卷 (卷一)',
    'Diplôme d\\'Études en Langue Française — Niveau A2 (Session 1)',
    '初级独立运用阶段：房产租房广告解读、博物馆活动通告、电话留言听取与短文细节捕捉。', 45, false),
  buildAuthenticFullPaper(312, 'delf', 'DELF A2', '法国国际教育研究中心 (FEI)', '官方冲刺卷',
    'DELF A2 官方短篇叙事与广播原声精炼卷 (卷二)',
    'Diplôme d\\'Études en Langue Française — Niveau A2 (Session 2)',
    '涵盖个人经历叙述、旅游行程咨询、周末休闲安排与公共交通变动通告。', 45, false),
  buildAuthenticFullPaper(313, 'delf', 'DELF A2', '法国国际教育研究中心 (FEI)', '官方精编卷',
    'DELF A2 旅游交通与公共服务实用机考卷 (卷三)',
    'Diplôme d\\'Études en Langue Française — Niveau A2 (Session 3)',
    '强化法国日常生活自主解决能力：邮局寄件、租车合约、文化活动预约事实提取。', 45, false),
  buildAuthenticFullPaper(314, 'delf', 'DELF A2', '法国国际教育研究中心 (FEI)', '官方拓展卷',
    'DELF A2 休闲文化与社区通告解读测试卷 (卷四)',
    'Diplôme d\\'Études en Langue Française — Niveau A2 (Session 4)',
    '法国社区生活、假期露营规则、文化活动宣传单与火车站晚点广播听解。', 45, false),
  buildAuthenticFullPaper(315, 'delf', 'DELF A2', '法国国际教育研究中心 (FEI)', '官方职场卷',
    'DELF A2 职场初阶邮件与业务预约大卷 (卷五)',
    'Diplôme d\\'Études en Langue Française — Niveau A2 (Session 5)',
    '商务初阶请假邮件、会议日程表解读、客户简单问询与电话留言记录。', 45, false),
  buildAuthenticFullPaper(316, 'delf', 'DELF A2', '法国国际教育研究中心 (FEI)', '官方旅游卷',
    'DELF A2 假日旅行游记与住宿体验精选卷 (卷六)',
    'Diplôme d\\'Études en Langue Française — Niveau A2 (Session 6)',
    '法国家庭式旅馆评价、退换货说明解读、法国自然公园景点导览。', 45, false),
  buildAuthenticFullPaper(317, 'delf', 'DELF A2', '法国国际教育研究中心 (FEI)', '官方青年卷',
    'DELF A2 法国青年志愿服务与环保倡议卷 (卷七)',
    'Diplôme d\\'Études en Langue Française — Niveau A2 (Session 7)',
    '法国青年环保协会公告、跳蚤市集二手交易须知与文化沙龙海报。', 45, false),
  buildAuthenticFullPaper(318, 'delf', 'DELF A2', '法国国际教育研究中心 (FEI)', '考前冲刺卷',
    'DELF A2 官方考前全真模拟综合冲刺大卷 (卷八)',
    'Diplôme d\\'Études en Langue Française — Niveau A2 (Session 8)',
    'A2 独立运用阶段全真仿真大卷，检验掌握过去时态叙事与公共信息提取。', 45, false),

  // 3. DELF B1 独立运用级大卷 (赴法留学/工作主力考级 10套)
  buildAuthenticFullPaper(321, 'delf', 'DELF B1', '法国国际教育研究中心 (FEI)', '官方标准卷',
    'DELF B1 官方社会热点与电台访谈精选卷 (卷一)',
    'Diplôme d\\'Études en Langue Française — Niveau B1 (Session 1)',
    'B1 进阶核心卷：法国电台原声专访听解（四天工作制探讨）、媒体热点报道与观点推断。', 60, false),
  buildAuthenticFullPaper(322, 'delf', 'DELF B1', '法国国际教育研究中心 (FEI)', '官方冲刺卷',
    'DELF B1 官方深度论点分析与事实推断卷 (卷二)',
    'Diplôme d\\'Études en Langue Française — Niveau B1 (Session 2)',
    '考察独立阐述见解与权衡利弊能力：环保生活方式、数字设备对青少年影响及论说阅读。', 60, false),
  buildAuthenticFullPaper(323, 'delf', 'DELF B1', '法国国际教育研究中心 (FEI)', '官方精编卷',
    'DELF B1 官方职场交流与文化新闻机考卷 (卷三)',
    'Diplôme d\\'Études en Langue Française — Niveau B1 (Session 3)',
    '职场正式邮件往来、员工培训通知解读、法国艺术展览新闻及社会趋势分析。', 60, false),
  buildAuthenticFullPaper(324, 'delf', 'DELF B1', '法国国际教育研究中心 (FEI)', '官方提升卷',
    'DELF B1 青年社会参与与数字化生活大卷 (卷四)',
    'Diplôme d\\'Études en Langue Française — Niveau B1 (Session 4)',
    '聚焦欧洲青年志愿活动、绿色生活方式与社交媒体健康使用，训练观点辨析力。', 60, false),
  buildAuthenticFullPaper(325, 'delf', 'DELF B1', '法国国际教育研究中心 (FEI)', '官方生态卷',
    'DELF B1 城市低碳微出行与共享经济大卷 (卷五)',
    'Diplôme d\\'Études en Langue Française — Niveau B1 (Session 5)',
    '共享单车治理、塞纳河两岸低碳慢行区建设、法国生态转型民意调查分析。', 60, false),
  buildAuthenticFullPaper(326, 'delf', 'DELF B1', '法国国际教育研究中心 (FEI)', '官方职场卷',
    'DELF B1 远程办公与现代家庭生活平衡测试卷 (卷六)',
    'Diplôme d\\'Études en Langue Française — Niveau B1 (Session 6)',
    '居家办公利弊思辨、劳动法离线权保障、员工身心健康关怀社会报道。', 60, false),
  buildAuthenticFullPaper(327, 'delf', 'DELF B1', '法国国际教育研究中心 (FEI)', '官方文化卷',
    'DELF B1 传统手工艺传承与当代商业创新大卷 (卷七)',
    'Diplôme d\\'Études en Langue Française — Niveau B1 (Session 7)',
    '法国青年返乡创业、传统烘焙与葡萄酒酿造工艺数字化转型深度报道。', 60, false),
  buildAuthenticFullPaper(328, 'delf', 'DELF B1', '法国国际教育研究中心 (FEI)', '官方学术卷',
    'DELF B1 当代青年阅读习惯与数字化演变大卷 (卷八)',
    'Diplôme d\\'Études en Langue Française — Niveau B1 (Session 8)',
    '法国国家图书中心调研报告：纸质书依恋情结 vs 电子书与播客阅读。', 60, false),
  buildAuthenticFullPaper(329, 'delf', 'DELF B1', '法国国际教育研究中心 (FEI)', '官方留学卷',
    'DELF B1 欧洲跨文化交流与留学生活适应大卷 (卷九)',
    'Diplôme d\\'Études en Langue Française — Niveau B1 (Session 9)',
    '大学校园国际交流周、Erasmus 欧洲交换生体验与跨文化沟通策略。', 60, false),
  buildAuthenticFullPaper(330, 'delf', 'DELF B1', '法国国际教育研究中心 (FEI)', '考前冲刺卷',
    'DELF B1 官方终身认证考前冲刺全真机考大卷 (卷十)',
    'Diplôme d\\'Études en Langue Française — Niveau B1 (Session 10)',
    '严格依据法国最新 DELF 机考标准编制，全面测试听力事实提取与长篇论述推理。', 60, false),

  // 4. DELF B2 进阶独立级大卷 (法硕/公派/高管必备 10套)
  buildAuthenticFullPaper(331, 'delf', 'DELF B2', '法国国际教育研究中心 (FEI)', '官方标准卷',
    'DELF B2 官方学术论辩与科技伦理高级测试卷 (卷一)',
    'Diplôme d\\'Études en Langue Française — Niveau B2 (Session 1)',
    '面向高阶独立运用者与赴法读研考生：人工智能与就业变革学术辩论、伦理法律深读。', 75, false),
  buildAuthenticFullPaper(332, 'delf', 'DELF B2', '法国国际教育研究中心 (FEI)', '官方冲刺卷',
    'DELF B2 官方生态法治与当代思辨高级测试卷 (卷二)',
    'Diplôme d\\'Études en Langue Française — Niveau B2 (Session 2)',
    '高难度批判性阅读与听解：气候正义、城市韧性规划与全球化经济模式转型研读。', 75, false),
  buildAuthenticFullPaper(333, 'delf', 'DELF B2', '法国国际教育研究中心 (FEI)', '官方精选大卷',
    'DELF B2 国际欧标深度综合论述冲刺大卷 (卷三)',
    'Diplôme d\\'Études en Langue Française — Niveau B2 (Session 3)',
    '法国原版社论与前沿人文大文，全方位对标法国大学入学语言门槛考核。', 75, false),
  buildAuthenticFullPaper(334, 'delf', 'DELF B2', '法国国际教育研究中心 (FEI)', '官方高阶卷',
    'DELF B2 人文哲学与经济转型深度辨析大卷 (卷四)',
    'Diplôme d\\'Études en Langue Française — Niveau B2 (Session 4)',
    '攻克高难度社论与学术访谈，掌握论据辨析、作者隐含立场推断与复杂逻辑衔接。', 75, false),
  buildAuthenticFullPaper(335, 'delf', 'DELF B2', '法国国际教育研究中心 (FEI)', '官方学术卷',
    'DELF B2 生物多样性危机与欧洲绿色新政大卷 (卷五)',
    'Diplôme d\\'Études en Langue Française — Niveau B2 (Session 5)',
    '农业生态转型与全球供应链脱碳、欧盟碳关税机制学术研讨深度听解与阅读。', 75, false),
  buildAuthenticFullPaper(336, 'delf', 'DELF B2', '法国国际教育研究中心 (FEI)', '官方媒介卷',
    'DELF B2 算法推荐与公共舆论空间重构思辨大卷 (卷六)',
    'Diplôme d\\'Études en Langue Française — Niveau B2 (Session 6)',
    '信息茧房现象剖析、新闻客观性反思、生成式人工智能在新闻媒体中的伦理边界。', 75, false),
  buildAuthenticFullPaper(337, 'delf', 'DELF B2', '法国国际教育研究中心 (FEI)', '官方高教卷',
    'DELF B2 高等教育国际化与科研评估机制大卷 (卷七)',
    'Diplôme d\\'Études en Langue Française — Niveau B2 (Session 7)',
    '全球大学排名批判、跨学科研究价值、学术论文开放获取 (Open Access) 运动。', 75, false),
  buildAuthenticFullPaper(338, 'delf', 'DELF B2', '法国国际教育研究中心 (FEI)', '官方哲学卷',
    'DELF B2 消费主义批判与极简低碳生活哲学大卷 (卷八)',
    'Diplôme d\\'Études en Langue Française — Niveau B2 (Session 8)',
    '快时尚生产链反思、零废弃循环经济、当代欧洲青年反消费主义心理机制。', 75, false),
  buildAuthenticFullPaper(339, 'delf', 'DELF B2', '法国国际教育研究中心 (FEI)', '官方文博卷',
    'DELF B2 文化遗产数字化与知识公有领域大卷 (卷九)',
    'Diplôme d\\'Études en Langue Française — Niveau B2 (Session 9)',
    '世界级博物馆文物数字化归属权、历史古迹虚拟重建、文化多样性条约解读。', 75, false),
  buildAuthenticFullPaper(340, 'delf', 'DELF B2', '法国国际教育研究中心 (FEI)', '考前冲刺卷',
    'DELF B2 赴法留学与高端岗位申请终极模拟大卷 (卷十)',
    'Diplôme d\\'Études en Langue Française — Niveau B2 (Session 10)',
    '对标法国高商 (HEC/ESSEC) 及顶尖公立大学学术语言标准，攻坚 75+ 高分。', 75, false),

  // 5. DALF C1 高级学术与职业精英级大卷 (法学/博士/外交必备 6套)
  buildAuthenticFullPaper(341, 'delf', 'DALF C1', '法国国际教育研究中心 (FEI)', '官方学术卷',
    'DALF C1 高等人文学术与现代性危机综合测试卷 (卷一)',
    'Diplôme Approfondi de Langue Française — Niveau C1 (Session 1)',
    '攻克高阶学术法语：现代个体疏离感、法兰克福学派批判理论长篇社论辨析。', 90, false),
  buildAuthenticFullPaper(342, 'delf', 'DALF C1', '法国国际教育研究中心 (FEI)', '官方地缘卷',
    'DALF C1 欧洲一体化与全球地缘政治深度辨析大卷 (卷二)',
    'Diplôme Approfondi de Langue Française — Niveau C1 (Session 2)',
    '多边主义重建、欧洲战略自主权、国际公法框架下的主权债务与环境人权。', 90, false),
  buildAuthenticFullPaper(343, 'delf', 'DALF C1', '法国国际教育研究中心 (FEI)', '官方前沿卷',
    'DALF C1 科技奇点与人类认知演进前沿学术大卷 (卷三)',
    'Diplôme Approfondi de Langue Française — Niveau C1 (Session 3)',
    '强人工智能对主体意识的解构、脑机接口哲学伦理、认知语言学前沿专著研读。', 90, false),
  buildAuthenticFullPaper(344, 'delf', 'DALF C1', '法国国际教育研究中心 (FEI)', '官方伦理卷',
    'DALF C1 法律规制与生命科学前沿治理高阶大卷 (卷四)',
    'Diplôme Approfondi de Langue Française — Niveau C1 (Session 4)',
    '基因编辑全球治理法学辩论、人工智能司法辅助系统合法性与正义论探析。', 90, false),
  buildAuthenticFullPaper(345, 'delf', 'DALF C1', '法国国际教育研究中心 (FEI)', '官方文艺卷',
    'DALF C1 文学批评与当代法国哲学思潮精析大卷 (卷五)',
    'Diplôme Approfondi de Langue Française — Niveau C1 (Session 5)',
    '解构主义文学理论、当代法语世界后殖民文学叙事、美学意象的文化符号学读解。', 90, false),
  buildAuthenticFullPaper(346, 'delf', 'DALF C1', '法国国际教育研究中心 (FEI)', '考前终极卷',
    'DALF C1 官方最高学术等级终极全真机考冲刺大卷 (卷六)',
    'Diplôme Approfondi de Langue Française — Niveau C1 (Session 6)',
    '全方位检验学术长文宏观构架概括力、隐含论点推论力与微言大义辨析力。', 90, false),`;

// Replace the old DELF block completely
code = code.replace(
  /\/\/ 七、法国官方 DELF[\s\S]*?buildAuthenticFullPaper\(314,[\s\S]*?\),/,
  DELF_FULL_42_PAPERS
);

// Append extra university papers before the array closes
code = code.replace(/buildAuthenticFullPaper\(412,[\s\S]*?\)\s*\];/, (match) => {
  return match.replace('];', ',\n' + EXTRA_UNIVERSITY_PAPERS + '\n];');
});

// Update export variable name
code = code.replaceAll('ALL_77_PAPERS', 'ALL_PAPERS');
code = code.replaceAll('ALL_100_PAPERS', 'ALL_PAPERS');
code = code.replaceAll('77套', '126套');
code = code.replaceAll('77 套', '126 套');
code = code.replaceAll('(241/242/243)', '');
code = code.replace(/SUCCESS_.*?TOTAL_PAPERS_.*?;/g, 'console.log("SUCCESS_PAPERS_GENERATED_" + ALL_PAPERS.length);');

fs.writeFileSync(path.resolve(__dirname, 'generate_all_exams.cjs'), code, 'utf-8');
console.log('generate_all_exams.cjs created successfully!');
